version: '3.8'

services:
  web:
    build: .
    ports:
      - "1532:1532"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    command: >
      sh -c "python database/init_db.py && python app.py"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor`
      MYSQL_DATABASE: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
